[package]
name = "tarin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
dotenv = "0.15.0"
serde_json = "1.0.140"
